// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: enauC2JUZgx5ZyyeLXbdDM
// Component: xpNItL138qnk6M
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_fine_line_charters.module.css"; // plasmic-import: enauC2JUZgx5ZyyeLXbdDM/projectcss
import sty from "./PlasmicRating.module.css"; // plasmic-import: xpNItL138qnk6M/css
import EmptyStarIcon from "./icons/PlasmicIcon__EmptyStar"; // plasmic-import: JWz7XDsBEMngMw/icon
import FullStarIcon from "./icons/PlasmicIcon__FullStar"; // plasmic-import: vT_2hCCN7W4RC3/icon
import HalfStarIcon from "./icons/PlasmicIcon__HalfStar"; // plasmic-import: G6PjFLKfMhDDhd/icon

export const PlasmicRating__VariantProps = new Array("rating");

export const PlasmicRating__ArgProps = new Array();

function PlasmicRating__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;
  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <p.PlasmicIcon
        PlasmicIconType={
          hasVariant(variants, "rating", "threeHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "twoHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "oneHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "half")
            ? HalfStarIcon
            : hasVariant(variants, "rating", "five")
            ? FullStarIcon
            : hasVariant(variants, "rating", "four")
            ? FullStarIcon
            : hasVariant(variants, "rating", "three")
            ? FullStarIcon
            : hasVariant(variants, "rating", "two")
            ? FullStarIcon
            : hasVariant(variants, "rating", "fourHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "one")
            ? FullStarIcon
            : EmptyStarIcon
        }
        className={classNames(projectcss.all, sty.svg__oHsCk, {
          [sty.svgrating_five__oHsCke1Cbk]: hasVariant(
            variants,
            "rating",
            "five"
          ),

          [sty.svgrating_fourHalf__oHsCkdOcuA]: hasVariant(
            variants,
            "rating",
            "fourHalf"
          ),

          [sty.svgrating_four__oHsCksKpR]: hasVariant(
            variants,
            "rating",
            "four"
          ),

          [sty.svgrating_half__oHsCKriiB4]: hasVariant(
            variants,
            "rating",
            "half"
          ),

          [sty.svgrating_oneHalf__oHsCkOmh]: hasVariant(
            variants,
            "rating",
            "oneHalf"
          ),

          [sty.svgrating_one__oHsCKyf92]: hasVariant(variants, "rating", "one"),
          [sty.svgrating_threeHalf__oHsCk6PQjM]: hasVariant(
            variants,
            "rating",
            "threeHalf"
          ),

          [sty.svgrating_three__oHsCkt7IJh]: hasVariant(
            variants,
            "rating",
            "three"
          ),

          [sty.svgrating_twoHalf__oHsCk2JWso]: hasVariant(
            variants,
            "rating",
            "twoHalf"
          ),

          [sty.svgrating_two__oHsCkj3ZKf]: hasVariant(variants, "rating", "two")
        })}
        role={"img"}
      />

      <p.PlasmicIcon
        PlasmicIconType={
          hasVariant(variants, "rating", "threeHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "twoHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "oneHalf")
            ? HalfStarIcon
            : hasVariant(variants, "rating", "five")
            ? FullStarIcon
            : hasVariant(variants, "rating", "four")
            ? FullStarIcon
            : hasVariant(variants, "rating", "three")
            ? FullStarIcon
            : hasVariant(variants, "rating", "two")
            ? FullStarIcon
            : hasVariant(variants, "rating", "fourHalf")
            ? FullStarIcon
            : EmptyStarIcon
        }
        className={classNames(projectcss.all, sty.svg__vElCq, {
          [sty.svgrating_five__vElCqE1Cbk]: hasVariant(
            variants,
            "rating",
            "five"
          ),

          [sty.svgrating_fourHalf__vElCqDOcuA]: hasVariant(
            variants,
            "rating",
            "fourHalf"
          ),

          [sty.svgrating_four__vElCqSKpR]: hasVariant(
            variants,
            "rating",
            "four"
          ),

          [sty.svgrating_oneHalf__vElCqOmh]: hasVariant(
            variants,
            "rating",
            "oneHalf"
          ),

          [sty.svgrating_threeHalf__vElCq6PQjM]: hasVariant(
            variants,
            "rating",
            "threeHalf"
          ),

          [sty.svgrating_three__vElCqT7IJh]: hasVariant(
            variants,
            "rating",
            "three"
          ),

          [sty.svgrating_twoHalf__vElCq2JWso]: hasVariant(
            variants,
            "rating",
            "twoHalf"
          ),

          [sty.svgrating_two__vElCqJ3ZKf]: hasVariant(variants, "rating", "two")
        })}
        role={"img"}
      />

      <p.PlasmicIcon
        PlasmicIconType={
          hasVariant(variants, "rating", "threeHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "twoHalf")
            ? HalfStarIcon
            : hasVariant(variants, "rating", "five")
            ? FullStarIcon
            : hasVariant(variants, "rating", "four")
            ? FullStarIcon
            : hasVariant(variants, "rating", "three")
            ? FullStarIcon
            : hasVariant(variants, "rating", "fourHalf")
            ? FullStarIcon
            : EmptyStarIcon
        }
        className={classNames(projectcss.all, sty.svg__qtORs, {
          [sty.svgrating_five__qtORsE1Cbk]: hasVariant(
            variants,
            "rating",
            "five"
          ),

          [sty.svgrating_fourHalf__qtORsDOcuA]: hasVariant(
            variants,
            "rating",
            "fourHalf"
          ),

          [sty.svgrating_four__qtORsSKpR]: hasVariant(
            variants,
            "rating",
            "four"
          ),

          [sty.svgrating_threeHalf__qtORs6PQjM]: hasVariant(
            variants,
            "rating",
            "threeHalf"
          ),

          [sty.svgrating_three__qtORsT7IJh]: hasVariant(
            variants,
            "rating",
            "three"
          ),

          [sty.svgrating_twoHalf__qtORs2JWso]: hasVariant(
            variants,
            "rating",
            "twoHalf"
          )
        })}
        role={"img"}
      />

      <p.PlasmicIcon
        PlasmicIconType={
          hasVariant(variants, "rating", "threeHalf")
            ? HalfStarIcon
            : hasVariant(variants, "rating", "five")
            ? FullStarIcon
            : hasVariant(variants, "rating", "four")
            ? FullStarIcon
            : hasVariant(variants, "rating", "fourHalf")
            ? FullStarIcon
            : EmptyStarIcon
        }
        className={classNames(projectcss.all, sty.svg___2ZbH, {
          [sty.svgrating_five___2ZbHe1Cbk]: hasVariant(
            variants,
            "rating",
            "five"
          ),

          [sty.svgrating_fourHalf___2ZbHdOcuA]: hasVariant(
            variants,
            "rating",
            "fourHalf"
          ),

          [sty.svgrating_four___2ZbHsKpR]: hasVariant(
            variants,
            "rating",
            "four"
          ),

          [sty.svgrating_threeHalf___2ZbH6PQjM]: hasVariant(
            variants,
            "rating",
            "threeHalf"
          )
        })}
        role={"img"}
      />

      <p.PlasmicIcon
        PlasmicIconType={
          hasVariant(variants, "rating", "five")
            ? FullStarIcon
            : hasVariant(variants, "rating", "fourHalf")
            ? HalfStarIcon
            : EmptyStarIcon
        }
        className={classNames(projectcss.all, sty.svg__dKt4T, {
          [sty.svgrating_five__dKt4Te1Cbk]: hasVariant(
            variants,
            "rating",
            "five"
          ),

          [sty.svgrating_fourHalf__dKt4TdOcuA]: hasVariant(
            variants,
            "rating",
            "fourHalf"
          )
        })}
        role={"img"}
      />
    </p.Stack>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicRating__ArgProps,
      internalVariantPropNames: PlasmicRating__VariantProps
    });

    return PlasmicRating__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRating";
  } else {
    func.displayName = `PlasmicRating.${nodeName}`;
  }
  return func;
}

export const PlasmicRating = Object.assign(
  // Top-level PlasmicRating renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicRating
    internalVariantProps: PlasmicRating__VariantProps,
    internalArgProps: PlasmicRating__ArgProps
  }
);

export default PlasmicRating;
/* prettier-ignore-end */
