// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: enauC2JUZgx5ZyyeLXbdDM
// Component: 5sSXh73L87u3W4
import * as React from "react";
import Link from "next/link";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { useScreenVariants as useScreenVariantsllkaOhQ1Bc8EW } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: LLKAOh_Q1bc8eW/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_fine_line_charters.module.css"; // plasmic-import: enauC2JUZgx5ZyyeLXbdDM/projectcss
import sty from "./PlasmicShopingSection.module.css"; // plasmic-import: 5sSXh73L87u3W4/css
import RightArrowIcon from "./icons/PlasmicIcon__RightArrow"; // plasmic-import: cV6OVkXZsVBTXg/icon

export const PlasmicShopingSection__VariantProps = new Array();

export const PlasmicShopingSection__ArgProps = new Array();

function PlasmicShopingSection__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsllkaOhQ1Bc8EW()
  });

  return (
    <section
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <p.Stack
        as={"div"}
        data-plasmic-name={"container433"}
        data-plasmic-override={overrides.container433}
        hasGap={true}
        className={classNames(projectcss.all, sty.container433)}
      >
        <div className={classNames(projectcss.all, sty.column__mx8N5)}>
          {true ? (
            <p.Stack
              as={"div"}
              data-plasmic-name={"freeBox"}
              data-plasmic-override={overrides.freeBox}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox)}
            >
              <h2
                data-plasmic-name={"h2"}
                data-plasmic-override={overrides.h2}
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2
                )}
              >
                {"Ready for your turn?"}
              </h2>

              {true ? (
                <p.Stack
                  as={p.PlasmicLink}
                  data-plasmic-name={"link"}
                  data-plasmic-override={overrides.link}
                  hasGap={true}
                  className={classNames(projectcss.all, projectcss.a, sty.link)}
                  component={Link}
                  href={"/item"}
                  platform={"nextjs"}
                >
                  <div
                    data-plasmic-name={"text"}
                    data-plasmic-override={overrides.text}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text
                    )}
                  >
                    {"Explore our Trips"}
                  </div>

                  <RightArrowIcon
                    data-plasmic-name={"svg"}
                    data-plasmic-override={overrides.svg}
                    className={classNames(projectcss.all, sty.svg)}
                    role={"img"}
                  />
                </p.Stack>
              ) : null}
            </p.Stack>
          ) : null}
        </div>

        <div className={classNames(projectcss.all, sty.column__a1Nm)}>
          <p.PlasmicImg
            data-plasmic-name={"img"}
            data-plasmic-override={overrides.img}
            alt={""}
            className={classNames(sty.img)}
            displayHeight={
              hasVariant(globalVariants, "screen", "mobileOnly")
                ? "320px /* plasmic-token: takHdVCPLxwfFE */"
                : "661px"
            }
            displayMaxHeight={"none"}
            displayMaxWidth={
              hasVariant(globalVariants, "screen", "mobileOnly")
                ? "100%"
                : "100%"
            }
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={
              hasVariant(globalVariants, "screen", "mobileOnly")
                ? "100%"
                : "783px"
            }
            loading={"lazy"}
            src={{
              src: "/plasmic/fine_line_charters/images/bentRodjpeg.jpeg",
              fullWidth: 1536,
              fullHeight: 2048,
              aspectRatio: undefined
            }}
          />
        </div>
      </p.Stack>
    </section>
  );
}

const PlasmicDescendants = {
  root: ["root", "container433", "freeBox", "h2", "link", "text", "svg", "img"],
  container433: ["container433", "freeBox", "h2", "link", "text", "svg", "img"],
  freeBox: ["freeBox", "h2", "link", "text", "svg"],
  h2: ["h2"],
  link: ["link", "text", "svg"],
  text: ["text"],
  svg: ["svg"],
  img: ["img"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicShopingSection__ArgProps,
      internalVariantPropNames: PlasmicShopingSection__VariantProps
    });

    return PlasmicShopingSection__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicShopingSection";
  } else {
    func.displayName = `PlasmicShopingSection.${nodeName}`;
  }
  return func;
}

export const PlasmicShopingSection = Object.assign(
  // Top-level PlasmicShopingSection renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    container433: makeNodeComponent("container433"),
    freeBox: makeNodeComponent("freeBox"),
    h2: makeNodeComponent("h2"),
    link: makeNodeComponent("link"),
    text: makeNodeComponent("text"),
    svg: makeNodeComponent("svg"),
    img: makeNodeComponent("img"),
    // Metadata about props expected for PlasmicShopingSection
    internalVariantProps: PlasmicShopingSection__VariantProps,
    internalArgProps: PlasmicShopingSection__ArgProps
  }
);

export default PlasmicShopingSection;
/* prettier-ignore-end */
